const P=[
{id:1,n:"Kola Real Piña 400 ml",b:"Kola Real",c:"Gaseosas",img:"https://vegaperu.vtexassets.com/arquivos/ids/159501/7750670013451.jpg?v=637835694155200000",u:3.9,pack:22.9,box:42.9,stock:62},
{id:2,n:"Kola Real Fresa 350 ml",b:"Kola Real",c:"Gaseosas",img:"https://www.mitiendaism.com/cdn/shop/files/KR-FRESA-350-ML.jpg?v=1754438735",u:1.2,pack:12.8,box:45.0,stock:88},
{id:3,n:"Agua Cielo 625 ml",b:"Cielo",c:"Aguas",img:"https://www.mitiendaism.com/cdn/shop/files/agua-sin-gas-cielo-625.jpg",u:1.5,pack:12,box:40,stock:128},
{id:4,n:"Sporade Naranja 625 ml",b:"Sporade",c:"Deportivas",img:"https://arteli.vtexassets.com/arquivos/ids/261376/7503027753018_00.jpg?v=638635820256370000",u:2.8,pack:30,box:58,stock:34},
{id:5,n:"360 Energy Drink Original 300 ml",b:"360",c:"Energizantes",img:"https://www.mitiendaism.com/cdn/shop/files/360-ORIGINAL-300-ML.jpg",u:2.0,pack:18.24,box:35,stock:41},
{id:6,n:"Cool Fresh Fresa 350 ml",b:"Cool Fresh",c:"Gaseosas",img:"https://www.mitiendaism.com/cdn/shop/files/COOL-FRESA-350-ML.jpg",u:1.2,pack:12.5,box:45,stock:76},
{id:7,n:"Kris Citrus Punch 350 ml",b:"Kris",c:"Jugos",img:"https://www.mitiendaism.com/cdn/shop/files/KRIS-CITRUS-PUNCH-350-ML.jpg",u:1.2,pack:12.5,box:45,stock:29},
{id:8,n:"Kris Tropical Punch 1 L",b:"Kris",c:"Jugos",img:"https://www.mitiendaism.com/cdn/shop/files/KRIS-TROPICAL-PUNCH-1-L.jpg",u:2.8,pack:25,box:47,stock:22},
{id:9,n:"Sabor de Oro",b:"Sabor de Oro",c:"Gaseosas",img:"https://www.mitiendaism.com/cdn/shop/files/SABOR-DE-ORO.jpg",u:2.5,pack:24,box:46,stock:45},
{id:10,n:"Generade",b:"Generade",c:"Funcionales",img:"https://www.mitiendaism.com/cdn/shop/files/GENERADE.jpg",u:2.5,pack:24,box:46,stock:31},
{id:11,n:"Cielo 1 L",b:"Cielo",c:"Aguas",img:"https://www.boticasperu.pe/on/demandware.static/-/Sites-boticasperu-master-catalog/default/dwcbfdd93e/images/19306.jpg",u:2.4,pack:20,box:40,stock:63},
{id:12,n:"Kero",b:"Kero",c:"Jugos",img:"https://www.mitiendaism.com/cdn/shop/files/KERO.jpg",u:2.5,pack:25,box:48,stock:25}
];
const knownBrands=["Todas","Kola Real","Cielo","Sporade","Cool Fresh","360","Kris","Sabor de Oro","Generade","Kero","Loa","Fruvi","Drink T","Black","Energina"];
let state={view:"home",brand:"Todas",role:"store",cart:JSON.parse(localStorage.getItem("ismCartFinal")||"[]"),user:JSON.parse(localStorage.getItem("ismUserFinal")||"null"),orders:JSON.parse(localStorage.getItem("ismOrdersFinal")||"[]")};
const $=s=>document.querySelector(s); const money=n=>"S/ "+n.toFixed(2);
function save(){localStorage.setItem("ismCartFinal",JSON.stringify(state.cart));localStorage.setItem("ismUserFinal",JSON.stringify(state.user));localStorage.setItem("ismOrdersFinal",JSON.stringify(state.orders));}
function toast(t){let e=$("#toast");e.className="toast show";e.textContent=t;setTimeout(()=>e.className="toast",1800)}
function header(){return `<header class="top"><div class="topline"><div><div class="logoText">ism<span>Directo</span></div><div class="hello">${state.user?`Hola, ${state.user.name.split(" ")[0]} 👋`:"Compra directo y recibe en tu negocio"}</div></div><div class="headicons"><button class="round" onclick="go('help')">💬</button><button class="round badge" onclick="openCart()">🛒<i>${state.cart.reduce((a,x)=>a+x.qty,0)}</i></button></div></div>${state.view!=="home"?`<div class="search"><span>⌕</span><input placeholder="Buscar productos, marcas..." oninput="searchProducts(this.value)"></div>`:""}</header>`}
function nav(){return `<nav class="bottom"><button class="${state.view==='home'?'active':''}" onclick="go('home')"><strong>⌂</strong>Inicio</button><button class="${state.view==='catalog'?'active':''}" onclick="go('catalog')"><strong>⌕</strong>Catálogo</button><button class="${state.view==='orders'?'active':''}" onclick="go('orders')"><strong>▣</strong>Pedidos</button><button class="${state.view==='promos'?'active':''}" onclick="go('promos')"><strong>★</strong>Ofertas</button><button class="${state.view==='profile'?'active':''}" onclick="go('profile')"><strong>♙</strong>Perfil</button></nav><button class="support" onclick="openSupport()">☏</button>`}
function home(){return `<div class="content"><section class="hero"><small>🚚 PEDIDOS DIRECTOS PARA TU NEGOCIO</small><h1>Tu negocio no puede quedarse sin stock.</h1><p>Compra tus productos ISM por unidad, pack o caja y recibe tu pedido donde lo necesitas.</p><button class="btn white cta" onclick="go('catalog')">Comprar ahora →</button><div class="heroProducts"><img src="${P[0].img}"><img src="${P[2].img}"><img src="${P[3].img}"></div></section><div class="sectionTitle"><h2>Compra por categoría</h2></div><div class="chips">${["Gaseosas","Aguas","Jugos","Deportivas","Energizantes","Funcionales"].map(x=>`<button class="chip" onclick="category('${x}')">${x}</button>`).join("")}</div><div class="sectionTitle"><h2>🔥 Los más vendidos</h2><button class="link" onclick="go('catalog')">Ver todos</button></div><div class="productGrid">${P.slice(0,4).map(card).join("")}</div><div class="sectionTitle"><h2>🎁 Promociones para tu tienda</h2></div><div class="promo"><div class="promoImg"><div><small>COMPRA MÁS, AHORRA MÁS</small><h2 style="margin:5px 0;font-size:21px">Precios especiales por volumen</h2><button class="btn yellow" onclick="go('promos')">Ver ofertas</button></div><img src="${P[1].img}"></div><div class="promoText"><small>PARA BODEGUEROS</small><h3>Arma tu pedido como quieras</h3><p>Elige unidad, pack o caja y revisa cuánto puedes ahorrar.</p></div></div><div class="sectionTitle"><h2>📦 Tu negocio, siempre abastecido</h2></div><div class="infoGrid"><div class="info"><b>24/7</b><span>Pedidos digitales</span></div><div class="info"><b>📍</b><span>Seguimiento</span></div><div class="info"><b>💬</b><span>Soporte</span></div></div></div>`}
function card(p){return `<article class="product"><div class="pimg"><img src="${p.img}" onerror="this.style.display='none'"></div><span class="brand">${p.b} · ${p.c}</span><h3>${p.n}</h3><div class="stock ${p.stock<20?'low':''}">● ${p.stock} disponibles</div><select class="select" id="format-${p.id}" onchange="showPrice(${p.id})"><option value="u">Unidad · ${money(p.u)}</option><option value="p">Pack · ${money(p.pack)}</option><option value="b">Caja · ${money(p.box)}</option></select><div class="price" id="price-${p.id}">${money(p.u)}</div><button class="add" onclick="add(${p.id})">Agregar al pedido</button></article>`}
function showPrice(id){let p=P.find(x=>x.id===id),v=$("#format-"+id).value;$("#price-"+id).textContent=money(v==="u"?p.u:v==="p"?p.pack:p.box)}
function catalog(){return `<div class="content"><h1 class="screenTitle">Catálogo</h1><p class="muted">Todo lo que necesitas para reponer tu tienda. Elige la presentación que más te convenga.</p><div class="chips">${knownBrands.map(x=>`<button class="chip ${state.brand===x?'active':''}" onclick="brand('${x}')">${x}</button>`).join("")}</div><div class="sectionTitle"><h2>${state.brand==="Todas"?"Productos disponibles":state.brand}</h2><span class="muted">${P.length} referencias</span></div><div class="productGrid" id="grid">${filtered().map(card).join("")}</div></div>`}
function filtered(){return state.brand==="Todas"?P:P.filter(p=>p.b===state.brand)}
function brand(b){state.brand=b;go("catalog")}
function category(c){state.brand="Todas";go("catalog");setTimeout(()=>{let q=c.toLowerCase();$("#grid").innerHTML=P.filter(p=>p.c.toLowerCase()===q).map(card).join("")},0)}
function searchProducts(q){let s=q.toLowerCase();$("#grid").innerHTML=P.filter(p=>(p.n+p.b+p.c).toLowerCase().includes(s)).map(card).join("")}
function promos(){return `<div class="content"><h1 class="screenTitle">Promociones</h1><p class="muted">Ofertas demostrativas pensadas para compras de tiendas.</p><div class="panel"><b>🔥 Compra por volumen</b><h2>5 cajas = descuento especial</h2><p class="muted">El beneficio puede variar según producto y campaña.</p><button class="btn red" onclick="go('catalog')">Armar pedido</button></div><div class="promo"><div class="promoImg"><div><small>PACK ESPECIAL</small><h2 style="margin:5px 0">KR + Cielo + Sporade</h2><button class="btn yellow" onclick="add(1);add(3);add(4)">Agregar combo</button></div><img src="${P[0].img}"></div></div><div class="sectionTitle"><h2>⭐ Beneficios para tiendas</h2></div><div class="infoGrid"><div class="info"><b>+PTS</b><span>Puntos por compra</span></div><div class="info"><b>📦</b><span>Compra por caja</span></div><div class="info"><b>🔔</b><span>Avisos de reposición</span></div></div></div>`}
function register(){return `<div class="content"><h1 class="screenTitle">Crear cuenta</h1><p class="muted">Regístrate en pocos pasos para comprar y recibir tus pedidos.</p><div class="panel"><div class="roles"><button class="role ${state.role==='store'?'active':''}" onclick="state.role='store';go('register')">🏪<b>Tienda / Bodega</b><small>Precios y compras por volumen</small></button><button class="role ${state.role==='person'?'active':''}" onclick="state.role='person';go('register')">👤<b>Consumidor</b><small>Compra para tu hogar</small></button></div></div><form class="panel form" onsubmit="registerUser(event)"><input class="input" id="name" required placeholder="Nombres y apellidos"><input class="input" id="dni" required maxlength="8" inputmode="numeric" placeholder="DNI"><input class="input" id="age" required type="number" min="1" placeholder="Edad"><input class="input" id="phone" required placeholder="Número de celular"><input class="input" id="email" type="email" required placeholder="Correo electrónico">${state.role==='store'?`<input class="input" id="business" required placeholder="Nombre comercial de la tienda"><select class="input" id="type"><option>Bodega</option><option>Minimarket</option><option>Restaurante</option><option>Otro negocio</option></select><input class="input" id="ruc" placeholder="RUC o DNI del titular">`:""}<input class="input" id="address" required placeholder="Dirección de entrega"><input class="input" id="ref" placeholder="Referencia"><button type="button" class="btn light" onclick="locationPermission()">📍 Usar mi ubicación</button><small id="loc" class="muted">Ubicación pendiente</small><div class="permission"><div><b>📍 Ubicación</b><span>Para mostrar la ubicación del repartidor y tu entrega.</span></div><button type="button" class="toggle" onclick="locationPermission()">Permitir</button></div><div class="permission"><div><b>💬 Mensajes</b><span>Para confirmaciones, promociones y estado del pedido.</span></div><button type="button" class="toggle" onclick="messagePermission()">Permitir</button></div><label class="check"><input type="checkbox" id="msg"> Quiero recibir avisos de pedidos y promociones.</label><label class="check"><input type="checkbox" required> Acepto los términos del prototipo.</label><button class="btn blue">Crear cuenta</button></form></div>`}
function locationPermission(){if(!navigator.geolocation){toast("Ubicación no disponible en este navegador");return}navigator.geolocation.getCurrentPosition(()=>{$("#loc").textContent="✓ Ubicación autorizada para el prototipo";toast("Permiso de ubicación concedido")},()=>toast("No se concedió el permiso"))}
async function messagePermission(){if(!("Notification" in window)){toast("Notificaciones no disponibles");return}let p=await Notification.requestPermission();toast(p==="granted"?"Notificaciones activadas":"Permiso no concedido")}
function registerUser(e){e.preventDefault();state.user={name:$("#name").value,dni:$("#dni").value,age:$("#age").value,phone:$("#phone").value,email:$("#email").value,address:$("#address").value};save();toast("Cuenta creada");setTimeout(()=>go("catalog"),500)}
function orders(){if(!state.orders.length)return `<div class="content"><h1 class="screenTitle">Mis pedidos</h1><div class="panel"><h3>Aún no tienes pedidos</h3><p class="muted">Haz tu primer pedido y podrás seguirlo desde aquí.</p><button class="btn blue" onclick="go('catalog')">Comprar</button></div></div>`;return `<div class="content"><h1 class="screenTitle">Seguimiento</h1>${state.orders.map((o,i)=>`<div class="panel"><div style="display:flex;justify-content:space-between"><div><span class="muted">${o.date}</span><h3 style="margin:4px 0">${o.id}</h3></div><b>${money(o.total)}</b></div><p class="muted">Estado: <b style="color:var(--blue)">${o.status}</b></p><div class="map"><span class="mapPin" style="left:17%;top:57%">🏪</span><span class="truck" style="left:${o.status==='Recibido'?38:o.status==='Preparando'?52:68}%;top:40%">🚚</span><span class="mapPin" style="left:80%;top:23%">📍</span><span class="road"></span><span class="maplabel">Llegada estimada: 20–30 min · ubicación simulada</span></div><div class="status"><span class="step active">Recibido</span><span class="step ${o.status!=='Recibido'?'active':''}">Preparando</span><span class="step ${o.status==='En camino'||o.status==='Entregado'?'active':''}">Camión en ruta</span><span class="step ${o.status==='Entregado'?'active':''}">Entregado</span></div><button class="btn light" onclick="advance(${i})">Simular siguiente estado</button></div>`).join("")}</div>`}
function advance(i){let a=["Recibido","Preparando","En camino","Entregado"],n=a.indexOf(state.orders[i].status);state.orders[i].status=a[Math.min(n+1,3)];save();go("orders");toast("Seguimiento actualizado")}
function profile(){return `<div class="content"><h1 class="screenTitle">Mi perfil</h1><div class="panel"><h3>${state.user?state.user.name:"Aún no estás registrado"}</h3><p class="muted">${state.user?state.user.phone+" · "+state.user.address:"Crea tu cuenta para gestionar tus pedidos."}</p><button class="btn blue" onclick="go('register')">${state.user?"Editar datos":"Registrarme"}</button></div><div class="panel"><b>🏪 Mi negocio</b><p class="muted">Tipo de cliente: ${state.role==="store"?"Tienda / Bodega":"Consumidor"}</p></div></div>`}
function help(){return `<div class="content"><h1 class="screenTitle">Ayuda y soporte</h1><p class="muted">Resuelve tus dudas o habla con un asesor.</p><div class="panel"><input class="input" placeholder="🔎 Buscar una pregunta..."><h3>Preguntas frecuentes</h3>${["¿Cómo hacer un pedido?","¿Cómo comprar por caja?","¿Cómo consulto el stock?","¿Cómo cambio la dirección?","¿Cómo rastreo mi pedido?","¿Qué métodos de pago hay?"].map(x=>`<button class="faq" onclick="toast('Respuesta disponible en la versión completa')">${x} <span>›</span></button>`).join("")}</div><div class="panel"><h3>¿Necesitas ayuda inmediata?</h3><button class="btn dark" style="width:100%;margin-bottom:8px" onclick="openSupport()">💬 Chat con soporte</button><button class="btn blue" style="width:100%" onclick="toast('Solicitud enviada a un asesor')">👤 Hablar con una persona</button></div></div>`}
function openSupport(){openModal(`<h2>💬 Soporte ISM</h2><div class="chat" id="chat"><div class="msg bot">Hola 👋 ¿En qué podemos ayudarte? Puedes preguntar por pedidos, stock, promociones o entregas.</div></div><div class="chatbar"><input class="input" id="chatIn" placeholder="Escribe tu pregunta..." onkeydown="if(event.key==='Enter')sendChat()"><button class="btn blue" onclick="sendChat()">Enviar</button></div><br><button class="btn dark" onclick="toast('Un asesor ha sido solicitado')">👤 Solicitar atención de una persona</button>`)}
function sendChat(){let x=$("#chatIn"),v=x.value.trim();if(!v)return;let c=$("#chat");c.innerHTML+=`<div class="msg me">${v}</div>`;let r=/stock/i.test(v)?"Puedes ver el stock debajo de cada producto.":/pedido|entrega|camión|camion/i.test(v)?"En Mis pedidos puedes ver y simular el recorrido del repartidor.":/caja|pack|precio/i.test(v)?"Cada producto permite elegir unidad, pack o caja.":"Puedo ayudarte con pedidos, stock, promociones y entregas.";setTimeout(()=>{c.innerHTML+=`<div class="msg bot">${r}</div>`;c.scrollTop=c.scrollHeight},300);x.value=""}
function openCart(){let total=state.cart.reduce((s,x)=>s+x.price*x.qty,0);openModal(`<h2>🛒 Tu pedido</h2>${state.cart.length?state.cart.map((x,i)=>{let p=P.find(z=>z.id===x.id);return `<div class="cartItem"><img src="${p.img}"><div><h4>${p.n}</h4><small>${x.type} · ${money(x.price)}</small></div><div class="qty"><button onclick="changeQty(${i},-1)">−</button>${x.qty}<button onclick="changeQty(${i},1)">+</button></div></div>`}).join("")+`<h2>Total: ${money(total)}</h2><button class="btn blue" style="width:100%" onclick="checkout()">Continuar</button>`:`<p class="muted">Tu carrito está vacío.</p><button class="btn blue" onclick="closeModal();go('catalog')">Ver productos</button>`}`)}
function changeQty(i,d){state.cart[i].qty+=d;if(state.cart[i].qty<=0)state.cart.splice(i,1);save();openCart()}
function add(id){let p=P.find(x=>x.id===id),v=$("#format-"+id)?.value||"u",price=v==="u"?p.u:v==="p"?p.pack:p.box,type=v==="u"?"Unidad":v==="p"?"Pack":"Caja";let x=state.cart.find(a=>a.id===id&&a.type===type);x?x.qty++:state.cart.push({id,type,qty:1,price});save();toast("Producto agregado")}
function checkout(){if(!state.user){closeModal();go("register");toast("Primero crea tu cuenta");return}let total=state.cart.reduce((s,x)=>s+x.price*x.qty,0);openModal(`<h2>Finalizar compra</h2><p class="muted">Entrega en: ${state.user.address}</p><div class="form"><select class="input"><option>Hoy · 10:00–12:00</option><option>Hoy · 14:00–17:00</option><option>Mañana · 9:00–12:00</option></select><select class="input"><option>Efectivo contra entrega</option><option>Yape / Plin</option><option>Tarjeta</option><option>Transferencia</option></select><button class="btn blue" onclick="finish(${total})">Realizar pedido · ${money(total)}</button></div>`)}
function finish(total){state.orders.unshift({id:"ISM-"+Date.now().toString().slice(-6),date:new Date().toLocaleString("es-PE"),total,status:"Recibido"});state.cart=[];save();closeModal();go("orders");toast("¡Pedido registrado!")}
function openModal(c){$("#modalBox").innerHTML=`<button class="close" onclick="closeModal()">✕</button>${c}`;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
function go(v){state.view=v;render();window.scrollTo(0,0)}
function render(){let main=state.view==="home"?home():state.view==="catalog"?catalog():state.view==="promos"?promos():state.view==="orders"?orders():state.view==="register"?register():state.view==="profile"?profile():help();$("#app").innerHTML=`<div class="phone">${header()}${main}${nav()}</div>`}
render();