const products=[
{id:1,name:"Agua Cielo 625 ml",brand:"Cielo",cat:"Aguas",unit:1,pack:6,box:24,price:1.80,packPrice:10.50,boxPrice:40.00,stock:128,emoji:"💧"},
{id:2,name:"Agua Cielo 2.5 L",brand:"Cielo",cat:"Aguas",unit:1,pack:6,box:12,price:4.50,packPrice:25.00,boxPrice:46.00,stock:74,emoji:"💧"},
{id:3,name:"Kola Real Naranja 3 L",brand:"Kola Real",cat:"Gaseosas",unit:1,pack:6,box:12,price:7.50,packPrice:42.00,boxPrice:80.00,stock:51,emoji:"🥤"},
{id:4,name:"Kola Real Cola 3 L",brand:"Kola Real",cat:"Gaseosas",unit:1,pack:6,box:12,price:7.50,packPrice:42.00,boxPrice:80.00,stock:66,emoji:"🥤"},
{id:5,name:"Sporade 625 ml",brand:"Sporade",cat:"Deportivas",unit:1,pack:6,box:24,price:2.80,packPrice:15.50,boxPrice:58.00,stock:34,emoji:"🧃"},
{id:6,name:"Pulp 1 L",brand:"Pulp",cat:"Jugos",unit:1,pack:6,box:12,price:4.20,packPrice:23.00,boxPrice:43.00,stock:29,emoji:"🧃"},
{id:7,name:"KR Pack x6",brand:"KR",cat:"Gaseosas",unit:1,pack:6,box:12,price:7.50,packPrice:38.00,boxPrice:72.00,stock:17,emoji:"📦"},
{id:8,name:"Cielo 7 L",brand:"Cielo",cat:"Aguas",unit:1,pack:6,box:6,price:8.90,packPrice:48.00,boxPrice:45.00,stock:9,emoji:"💧"}
];
let cart=JSON.parse(localStorage.getItem("ism2cart")||"[]"),orders=JSON.parse(localStorage.getItem("ism2orders")||"[]"),user=JSON.parse(localStorage.getItem("ism2user")||"null"),view="inicio",accountType="tienda";
const money=n=>"S/ "+n.toFixed(2), save=()=>{localStorage.setItem("ism2cart",JSON.stringify(cart));localStorage.setItem("ism2orders",JSON.stringify(orders));localStorage.setItem("ism2user",JSON.stringify(user));count()};
function count(){document.getElementById("cartCount").textContent=cart.reduce((s,x)=>s+x.qty,0)}
function img(p){return `<div class="mock-img"><div class="bottle"><span>${p.emoji}</span><b>${p.brand}</b><small>${p.name.split(" ")[0]}</small></div></div>`}
function card(p){return `<article class="product">${p.stock<20?'<span class="tag">Últimas unidades</span>':''}<div class="product-img">${img(p)}</div><span class="muted">${p.brand} · ${p.cat}</span><h3>${p.name}</h3><div class="stock ${p.stock<20?'low':'ok'}">● ${p.stock} disponibles</div><div class="select-row"><select id="type${p.id}" onchange="priceChange(${p.id})"><option value="unit">Unidad</option><option value="pack">Pack x${p.pack}</option><option value="box">Caja x${p.box}</option></select><select id="qty${p.id}">${[1,2,3,4,5,10].map(x=>`<option>${x}</option>`).join("")}</select></div><div class="price" id="price${p.id}">${money(p.price)}</div><button class="btn dark" onclick="add(${p.id})">Agregar pedido</button></article>`}
function priceChange(id){let p=products.find(x=>x.id===id),t=document.getElementById("type"+id).value;document.getElementById("price"+id).textContent=money(t==="unit"?p.price:t==="pack"?p.packPrice:p.boxPrice)}
function add(id){let p=products.find(x=>x.id===id),t=document.getElementById("type"+id)?.value||"unit",q=+(document.getElementById("qty"+id)?.value||1),price=t==="unit"?p.price:t==="pack"?p.packPrice:p.boxPrice;let x=cart.find(i=>i.id===id&&i.type===t);x?x.qty+=q:cart.push({id,type:t,qty:q,price});save();toast("Agregado al carrito")}
function toast(s){let e=document.createElement("div");e.textContent=s;e.style="position:fixed;right:20px;bottom:20px;background:#17212b;color:#fff;padding:13px 17px;border-radius:10px;z-index:200;font-weight:800";document.body.appendChild(e);setTimeout(()=>e.remove(),1800)}
function home(){return `<section class="hero"><div><span>🚚 PEDIDOS DIRECTOS</span><h1>Abastece tu negocio de forma rápida y sencilla.</h1><p>Compra por unidad, pack o caja. Consulta stock, promociones, pedidos y simula el recorrido del repartidor.</p><button class="btn primary" onclick="view='catalogo';render()">Comprar ahora</button> <button class="btn outline" onclick="view='registro';render()">Crear cuenta</button><div class="hero-mini"><div class="mini"><b>📦 Compra por volumen</b><br><small>Precios por pack y caja</small></div><div class="mini"><b>📍 Rastrea</b><br><small>Simulación de entrega</small></div><div class="mini"><b>💬 Soporte</b><br><small>Chat y asesor</small></div></div></div><div class="hero-side"><h3>🚚 Tu próximo pedido</h3><p>Simula dónde está el repartidor.</p><div class="map"><span class="pin" style="left:24%;top:58%">🏪</span><span class="truck" style="left:57%;top:42%">🚚</span><span class="pin" style="left:78%;top:25%">📍</span><span class="route"></span></div><p><b>En camino</b> · llegada estimada 20–30 min</p></div></section>
<section class="section"><div class="section-head"><h2>🔥 Más vendidos</h2><button class="btn light" onclick="view='catalogo';render()">Ver catálogo</button></div><div class="cards">${products.slice(0,4).map(card).join("")}</div></section>
<section class="section"><div class="grid2"><div class="promo"><strong>OFERTA PARA TIENDAS</strong><h2>Compra por caja y ahorra</h2><p>Compara unidad, pack y caja antes de agregar al carrito.</p><button class="btn red" onclick="view='catalogo';render()">Ver precios por volumen</button></div><div class="promo"><strong>⭐ REPOSICIÓN</strong><h2>¿Te quedaste sin stock?</h2><p>Consulta productos disponibles y vuelve a pedir tus productos frecuentes.</p><button class="btn dark" onclick="view='pedidos';render()">Revisar pedidos</button></div></div></section>`}
function catalog(){return `<section class="section"><h1>Catálogo de productos</h1><p class="muted">Elige presentación: unidad, pack o caja.</p><input class="search" placeholder="🔎 Buscar producto, marca o categoría..." oninput="filter(this.value)"><div class="filters"><button class="btn light active" onclick="filter('')">Todos</button><button class="btn light" onclick="filter('Cielo')">Cielo</button><button class="btn light" onclick="filter('Kola Real')">Kola Real</button><button class="btn light" onclick="filter('Sporade')">Sporade</button><button class="btn light" onclick="filter('Pulp')">Pulp</button><button class="btn light" onclick="filter('Gaseosas')">Gaseosas</button></div><div class="cards" id="grid">${products.map(card).join("")}</div></section>`}
function filter(q){let s=q.toLowerCase();document.getElementById("grid").innerHTML=products.filter(p=>(p.name+" "+p.brand+" "+p.cat).toLowerCase().includes(s)).map(card).join("")}
function promos(){return `<section class="section"><h1>Promociones y oportunidades</h1><p class="muted">Ejemplos de promociones para el prototipo.</p><div class="cards"><div class="promo"><strong>VOLUMEN</strong><h2>5 cajas de gaseosa</h2><p>Descuento simulado por compra mayorista.</p><h2>-10%</h2><button class="btn red" onclick="view='catalogo';render()">Comprar</button></div><div class="promo"><strong>PACK</strong><h2>Agua Cielo x6</h2><p>Presentación práctica para reposición.</p><h2>S/ 10.50</h2><button class="btn red" onclick="add(1)">Agregar</button></div><div class="promo"><strong>FIDELIDAD</strong><h2>Puntos por compra</h2><p>Acumula puntos y canjéalos por beneficios.</p><h2>+10 pts</h2><button class="btn dark" onclick="toast('Función demostrativa')">Ver puntos</button></div><div class="promo"><strong>REPOSICIÓN</strong><h2>Recordatorio inteligente</h2><p>Recibe un aviso cuando sea momento de volver a pedir.</p><button class="btn dark" onclick="notifyMe()">Activar avisos</button></div></div></section>`}
function register(){return `<section class="section"><div class="panel" style="max-width:720px;margin:auto"><h1>Crear tu cuenta</h1><p class="muted">Registro rápido según tu tipo de cliente.</p><div class="role"><button class="${accountType==='tienda'?'active':''}" onclick="accountType='tienda';render()">🏪 Tienda / Bodega</button><button class="${accountType==='persona'?'active':''}" onclick="accountType='persona';render()">👤 Consumidor</button></div><br><form class="form" onsubmit="reg(event)"><input id="fullname" required placeholder="Nombres y apellidos"><input id="dni" required maxlength="8" inputmode="numeric" placeholder="DNI"><input id="age" type="number" min="1" max="120" required placeholder="Edad"><input id="phone" required placeholder="Número de celular"><input id="email" type="email" required placeholder="Correo electrónico">${accountType==='tienda'?'<input id="business" required placeholder="Nombre comercial de la tienda"><select id="businessType"><option>Bodega</option><option>Minimarket</option><option>Restaurante</option></select><input id="ruc" placeholder="RUC o DNI del titular (opcional)">':''}<input id="address" required placeholder="Dirección de entrega"><input id="reference" placeholder="Referencia"><button type="button" class="btn light" onclick="getLocation()">📍 Usar mi ubicación actual</button><p id="locStatus" class="muted">Ubicación: pendiente de permiso</p><label><input type="checkbox" id="permMsg"> Permitir avisos y notificaciones de pedidos</label><label><input type="checkbox" required> Acepto los términos del prototipo</label><button class="btn red">Crear cuenta</button></form></div></section>`}
function reg(e){e.preventDefault();user={type:accountType,name:fullname.value,dni:dni.value,age:age.value,phone:phone.value,email:email.value,address:address.value,reference:reference.value};save();if(document.getElementById("permMsg")?.checked)notifyMe();toast("Cuenta creada correctamente");setTimeout(()=>{view="catalogo";render()},600)}
function getLocation(){if(!navigator.geolocation){document.getElementById("locStatus").textContent="Este navegador no permite ubicación";return}navigator.geolocation.getCurrentPosition(()=>document.getElementById("locStatus").textContent="✓ Ubicación autorizada (simulada en el prototipo)",()=>document.getElementById("locStatus").textContent="No se concedió el permiso")}
async function notifyMe(){if("Notification" in window){let p=await Notification.requestPermission();toast(p==="granted"?"Notificaciones activadas":"Notificaciones no activadas")}else toast("Notificaciones no disponibles en este navegador")}
function cartHTML(){let total=cart.reduce((s,i)=>s+i.price*i.qty,0);return `<button class="close" onclick="closeModal()">✕</button><h2>🛒 Tu carrito</h2>${cart.length?cart.map((i,n)=>{let p=products.find(x=>x.id===i.id);return `<div class="cart-row"><div><b>${p.name}</b><br><span class="muted">${i.type==='unit'?'Unidad':i.type==='pack'?'Pack x'+p.pack:'Caja x'+p.box}</span></div><div class="qty"><button onclick="qty(${n},-1)">−</button>${i.qty}<button onclick="qty(${n},1)">+</button></div><b>${money(i.price*i.qty)}</b></div>`}).join("")+`<h2>Total: ${money(total)}</h2><button class="btn red" onclick="checkout()">Continuar al pedido</button>`:`<p>Tu carrito está vacío.</p>`}`}
function openCart(){document.getElementById("modalContent").innerHTML=cartHTML();document.getElementById("modal").classList.remove("hidden")}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function qty(n,d){cart[n].qty+=d;if(cart[n].qty<=0)cart.splice(n,1);save();openCart()}
function checkout(){if(!user){closeModal();view="registro";render();toast("Primero crea tu cuenta");return}let total=cart.reduce((s,i)=>s+i.price*i.qty,0);document.getElementById("modalContent").innerHTML=`<button class="close" onclick="closeModal()">✕</button><h2>Confirmar pedido</h2><p>Entrega en: <b>${user.address}</b></p><div class="form"><select id="delivery"><option>Mañana · 9:00–12:00</option><option>Mañana · 14:00–17:00</option><option>Pasado mañana · 9:00–12:00</option></select><select id="pay"><option>Efectivo contra entrega</option><option>Yape / Plin</option><option>Transferencia</option><option>Tarjeta</option></select><button class="btn red" onclick="finish(${total})">Confirmar pedido · ${money(total)}</button></div>`}
function finish(total){orders.unshift({id:"ISM-"+Date.now().toString().slice(-6),date:new Date().toLocaleString("es-PE"),total,status:"Recibido",address:user.address});cart=[];save();closeModal();view="pedidos";render();toast("Pedido recibido")}
function pedidos(){if(!orders.length)return `<section class="section"><div class="panel"><h1>Mis pedidos</h1><p>Aún no tienes pedidos.</p><button class="btn red" onclick="view='catalogo';render()">Hacer pedido</button></div></section>`;return `<section class="section"><h1>Mis pedidos y rastreo</h1>${orders.map((o,i)=>`<div class="panel" style="margin-bottom:18px"><div class="section-head"><div><span class="muted">${o.date}</span><h2>${o.id}</h2></div><b>${money(o.total)}</b></div><p>Estado: <b>${o.status}</b> · 📍 ${o.address}</p><div class="map"><span class="pin" style="left:22%;top:56%">🏪</span><span class="truck" style="left:${o.status==='Recibido'?40:62}%;top:40%">🚚</span><span class="pin" style="left:80%;top:23%">📍</span><span class="route"></span></div><div class="steps"><span class="step active">Recibido</span><span class="step ${o.status!=='Recibido'?'active':''}">Preparando</span><span class="step ${o.status==='En camino'?'active':''}">Camión en ruta</span><span class="step">Entregado</span></div><button class="btn light" onclick="advance(${i})">Simular siguiente estado</button></div>`).join("")}</section>`}
function advance(i){let a=["Recibido","Preparando","En camino","Entregado"],n=a.indexOf(orders[i].status);orders[i].status=a[Math.min(n+1,3)];save();render();toast("Seguimiento actualizado")}
function ayuda(){return `<section class="section"><div class="grid2"><div class="panel"><h1>Centro de ayuda</h1><p class="muted">Respuestas rápidas y soporte.</p><div class="table-like"><button class="btn light" onclick="toast('Puedes modificar tu dirección desde Perfil en la versión completa')">¿Cómo cambio mi dirección?</button><button class="btn light" onclick="toast('El stock mostrado es demostrativo')">¿El stock es real?</button><button class="btn light" onclick="toast('Puedes elegir unidad, pack o caja desde Catálogo')">¿Cómo compro por caja?</button><button class="btn light" onclick="toast('El rastreo es una simulación para el prototipo')">¿Cómo sigo mi pedido?</button></div><br><button class="btn red" onclick="openSupport()">Hablar con un asesor</button></div><div class="panel"><h1>📊 Información para tiendas</h1><div class="stat-grid"><div class="stat"><span>Productos</span><b>8</b></div><div class="stat"><span>Disponibles</span><b>91%</b></div><div class="stat"><span>Más vendido</span><b>Cielo</b></div></div><h3>Productos más vendidos</h3><div class="row"><b>Producto</b><b>Pedidos</b><b>Stock</b></div><div class="row"><span>Agua Cielo</span><span>124</span><span>128</span></div><div class="row"><span>KR 3 L</span><span>97</span><span>66</span></div><div class="row"><span>Sporade</span><span>75</span><span>34</span></div></div></div></section>`}
function openSupport(){document.getElementById("modalContent").innerHTML=`<button class="close" onclick="closeModal()">✕</button><h2>💬 Soporte ISM Directo</h2><div class="chat" id="chat"><div class="msg bot">Hola 👋 Soy el asistente. Puedo ayudarte con pedidos, stock, promociones y entregas.</div></div><div class="chatbar"><input id="chatInput" placeholder="Escribe tu consulta..." onkeydown="if(event.key==='Enter')sendChat()"><button class="btn red" onclick="sendChat()">Enviar</button></div><hr><button class="btn dark" onclick="toast('Solicitud enviada a un asesor')">👤 Solicitar atención de una persona</button>`;document.getElementById("modal").classList.remove("hidden")}
function sendChat(){let input=document.getElementById("chatInput"),v=input.value.trim();if(!v)return;let c=document.getElementById("chat");c.innerHTML+=`<div class="msg me">${v}</div>`;let r="Puedo ayudarte. Para una atención personalizada, usa el botón de asesor.";if(/stock|producto/i.test(v))r="Puedes consultar el stock disponible directamente en cada producto del catálogo.";if(/pedido|entrega|camión|camion/i.test(v))r="En Mis pedidos puedes simular el estado y recorrido del repartidor.";if(/precio|caja|pack/i.test(v))r="En cada producto puedes elegir unidad, pack o caja y comparar el precio.";setTimeout(()=>{c.innerHTML+=`<div class="msg bot">${r}</div>`;c.scrollTop=c.scrollHeight},400);input.value=""}
function render(){let a=document.getElementById("app");a.innerHTML=view==="inicio"?home():view==="catalogo"?catalog():view==="promos"?promos():view==="pedidos"?pedidos():view==="registro"?register():ayuda();count()}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});render();
